PROFILE_WEIGHTS = {
    "iam": 6,
    "azure": 4,
    "cloud": 3,
    "infrastructure": 5,
    "systems": 5,
    "support": 3,
    "it": 2,
    "windows": 4,
    "microsoft": 3,
    "network": 3,
    "security": 2,
    "linux": 2,
    "admin": 4,
    "analyst": 3,
    "technician": 3,
    "devops": 1,
    "engineer_penalty": -2,
    "senior_penalty": -4,
    "developer_penalty": -4,
    "sales_penalty": -5,
    "marketing_penalty": -5,
    "design_penalty": -5,
    "writer_penalty": -5,
}

PROFILE_KEYWORDS = {
    "iam": [
        "iam",
        "identity",
        "identity access",
        "access management",
        "entra",
        "active directory",
        "okta",
    ],
    "azure": [
        "azure",
    ],
    "cloud": [
        "cloud",
        "cloud support",
        "cloud operations",
        "platform support",
    ],
    "infrastructure": [
        "infrastructure",
        "infra",
        "server",
        "servers",
        "endpoint",
        "workplace technology",
        "end user computing",
        "euc",
    ],
    "systems": [
        "system administrator",
        "systems administrator",
        "sysadmin",
        "systems engineer",
        "systems support",
        "it administrator",
        "infrastructure engineer",
    ],
    "support": [
        "support",
        "technical support",
        "it support",
        "desktop support",
        "help desk",
        "helpdesk",
        "service desk",
        "support analyst",
        "support technician",
    ],
    "it": [
        " it ",
        "information technology",
    ],
    "windows": [
        "windows",
        "intune",
        "autopilot",
        "sccm",
        "microsoft 365",
        "office 365",
        "o365",
        "exchange",
    ],
    "microsoft": [
        "microsoft",
        "teams",
        "sharepoint",
        "outlook",
    ],
    "network": [
        "network",
        "networking",
        "wifi",
        "lan",
        "wan",
        "dns",
        "dhcp",
        "tcp/ip",
        "vpn",
    ],
    "security": [
        "security",
        "endpoint security",
        "access control",
    ],
    "linux": [
        "linux",
        "ubuntu",
        "red hat",
        "rhel",
    ],
    "admin": [
        "administrator",
        "administration",
        "admin",
    ],
    "analyst": [
        "analyst",
    ],
    "technician": [
        "technician",
        "operator",
    ],
    "devops": [
        "devops",
        "sre",
        "platform engineer",
    ],
    "engineer_penalty": [
        "engineer",
    ],
    "senior_penalty": [
        "senior",
        "sr.",
        "lead",
        "principal",
        "staff",
        "architect",
        "manager",
        "head of",
        "director",
    ],
    "developer_penalty": [
        "developer",
        "software engineer",
        "full stack",
        "frontend",
        "backend",
        "ios developer",
        "android developer",
        "react developer",
        "ruby on rails",
    ],
    "sales_penalty": [
        "sales",
        "account executive",
        "business development",
        "sdr",
        "bdr",
    ],
    "marketing_penalty": [
        "marketing",
        "seo",
        "growth",
        "content marketing",
    ],
    "design_penalty": [
        "designer",
        "product designer",
        "ux",
        "ui",
    ],
    "writer_penalty": [
        "writer",
        "copywriter",
        "editor",
        "content reviewer",
    ],
}
